config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :categories
  resources :events
  resources :testimonis
  resources :sliders
  resources :news
  resources :contacts, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/event', to: 'home#event', as: :home_event
  get '/contact', to: 'home#contact', as: :home_contact
  get '/about', to: 'home#about', as: :home_about
  get '/client-says', to: 'home#testimonials', as: :home_testimo
  get '/event/:id', to: 'home#gallery', as: :category_event
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonis#all_testimoni', as: :all_testimoni
  get 'admin/users/', to: 'users#all_user', as: :all_user
  get 'admin/announcements/', to: 'news#all_news', as: :all_news
  get 'admin/users/change-password/:id', to: 'users#edit_password', as: :edit_password
  get 'admin/categories', to: 'categories#all_category', as: :all_category
  delete '/events/:event_id/galleries/:id', to: 'galleries#delt', as: :delete_gallery
  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :galleries, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :galleries, reject_if: :all_blank, allow_destroy: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :show]


  def new
    @event = current_user.events.build
    @categories = Category.all.order("name")
    @event.galleries.build
    render layout: "admin"
  end

  def create
    @event = current_user.events.build(params_event)
    if @event.save
      redirect_to all_event_url
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.order("name")
    render layout: "admin"
  end

  def update
    if @event.update(params_event)
      redirect_to new_event_url
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to all_event_url
  end

  def all_event
    @events = Event.all.order('created_at desc')
    render layout: "admin"
  end

  def show
    render layout: "admin"
  end


  private

  def set_event
    # @event = Event.friendly.find(params[:id])
    @event = Event.find(params[:id])
  end

  def params_event
    params.require(:event).permit(:name, :event_date, :category_id, galleries_attributes: [:image, :name, :category_id, :description, :_destroy])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f|  %>
  <div class="form-group">
    <%= f.label :name  %>
    <%= f.text_field :name, class: "form-control", autofocus: true  %>
  </div>

  <div class="form-group">
    <%= f.label :event_date  %>
    <%= f.date_field :event_date, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.fields_for :galleries do |gallery| %>
      <%= render 'gallery_fields', f: gallery %>
      <div class="links">
        <%= link_to_add_association 'Add Field', f, :galleries %>
      </div>
    <% end %>
  </div>
  <%= f.submit "Upload", class: "btn btn-default"  %>
<% end  %>

app/views/events/_gallery_fields.html.erb
<div class="nested-fields">
    <div class="field form-group">
      <%= f.label :image, "Photo" %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.collection_select(:category_id, @categories, :id, :name, {prompt: "Choose category"}, {class: "form-control form_cate"}) %>
    </div>
    <div class="field form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "Photo Name" %>
    </div>
    <div class="field form-group">
      <%= f.text_area :description, class: "form-control", placeholder: "Photo Description" %>
    </div>
    <%= link_to_remove_association "Remove Field", f %>
</div>

app/views/events/all_event.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">All Events</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_event_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_event_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <div class="row dashgy">
      <% @events.each do |event| %>
        <div class="col-xs-6 col-md-3">
          <a class="thumbnail">
            <% event.galleries.each_with_index do |f, index| %>
              <% if index == 0 %>
                <%= image_tag f.image_url(:thumb) %>
              <% end %>
            <% end %>
          </a>
          <div class="dagsjh">
            <ul class="list-inline lsj">
              <li><%= link_to edit_event_path(event), class: "edit" do %><i class="fa fa-pencil-square-o" aria-hidden="true"></i><% end %></li>
              <li class="sgf"><%= link_to event_url(event), class: "toitem" do %><i class="fa fa-paper-plane-o" aria-hidden="true"></i><% end %></li> 
              <li><%= link_to event, method: :delete, class: "destroy" do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></li>
            </ul>
          </div>
          <div class="caption">
            <h3><%= truncate(event.name, length: 20) %></h3>
          </div>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.event__').addClass('aktif');
</script>

app/views/events/edit.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">Edit Events</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_event_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_event_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render "events/form" %>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.event__').addClass('aktif');
</script>

app/views/events/new.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">Add New Events</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_event_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_event_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render "events/form" %>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.event__').addClass('aktif');
</script>

app/views/events/show.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title"><%= @event.name %></h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_event_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_event_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <div class="cont_ii">
      <div class="row dashgy">
        <% @event.galleries.each do |gallery| %>
          <div class="col-xs-6 col-md-3" id="gale_<%= gallery.id %>">
            <a class="thumbnail">
              <%= image_tag gallery.image_url(:thumb) %>
            </a>
            <div class="dagsjh">
              <ul class="list-inline lsj" style="padding-top: 27%;">
                <li><%= link_to delete_gallery_url(@event, gallery), method: :delete, class: "destroy" do %> <i class="fa fa-trash-o" aria-hidden="true"></i><% end %></li>
              </ul>
            </div>
            <div class="caption">
              <h3 title="<%= gallery.name %>"><%= truncate(gallery.name, length: 20) %></h3>
            </div>
          </div>
        <% end %>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.event__').addClass('aktif');
</script>