config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :categories
  resources :events
  resources :testimonis
  resources :sliders
  resources :news
  resources :contacts, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/event', to: 'home#event', as: :home_event
  get '/contact', to: 'home#contact', as: :home_contact
  get '/about', to: 'home#about', as: :home_about
  get '/client-says', to: 'home#testimonials', as: :home_testimo
  get '/event/:id', to: 'home#gallery', as: :category_event
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonis#all_testimoni', as: :all_testimoni
  get 'admin/users/', to: 'users#all_user', as: :all_user
  get 'admin/announcements/', to: 'news#all_news', as: :all_news
  get 'admin/users/change-password/:id', to: 'users#edit_password', as: :edit_password
  get 'admin/categories', to: 'categories#all_category', as: :all_category
  delete '/events/:event_id/galleries/:id', to: 'galleries#delt', as: :delete_gallery
  root 'home#index'

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  before_action :set_news, only: [:update, :edit, :destroy]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @news = News.new
    render layout: "admin"
  end

  def create
    @news = News.new(params_news)
    if @news.save
      redirect_to all_news_url
    else
      render 'new'
    end
  end

  def edit
    render layout: "admin"
  end

  def update
    if @news.update(params_news)
      redirect_to all_news_url
    else
      render 'edit'
    end
  end

  def destroy
    @news.destroy
    redirect_to all_news_url
  end

  def all_news
    @news = News.all.order('created_at desc')
    render layout: "admin"
  end

  private

  def set_news
    @news = News.find(params[:id])
  end

  def params_news
    params.require(:news).permit(:title, :content)
  end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for @news do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "Content" %>
  </div>
  <div class="btn_x">
    <%= f.submit "Upload", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/news/all_news.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">All Announcements</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_news_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_news_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <div class="testimonaial edbsg" style="width: 100%;">
      <div class="leyr titl">
        <p class="hsy">all the announcements that have been added <span class="pull-right hgdr"><%= @news.count %></span></p>
      </div>
      <div class="dhjwt">
        <ul class="cbdq">
          <% @news.each_with_index do |test, index| %>
            <li class="ang <%= 'cvdg' if (index + 1)%2 == 0 %>">
              <ul class="list-inline najhs">
                <li class="name_" style="width: 200px !important;"><%= truncate(test.title, length: 19) %></li>
                <li class="user_ content_" style="width: 570px !important"><%= truncate(test.content, length: 90) %></li>
                <li class="created_at_"  style="width: 135px !important; border-right: 1px solid #e7ebf1 !important;"><%= test.created_at.strftime("%d %B %Y") %></li>
                <li class="actions_">
                  <ul class="list-inline ahster">
                    <li><%= link_to edit_news_path(test) do %><i class="fa fa-pencil-square-o" aria-hidden="true"></i><% end %></li>
                    <li><%= link_to test, method: :delete do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></li>
                  </ul>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.news__').addClass('aktif');
</script>

app/views/news/edit.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">Add New Announcements</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_news_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_news_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render "news/form" %>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.news__').addClass('aktif');
</script>

app/views/news/new.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">Add New Announcements</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_news_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_news_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render "news/form" %>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.news__').addClass('aktif');
</script>