config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :categories
  resources :events
  resources :testimonis
  resources :sliders
  resources :news
  resources :contacts, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/event', to: 'home#event', as: :home_event
  get '/contact', to: 'home#contact', as: :home_contact
  get '/about', to: 'home#about', as: :home_about
  get '/client-says', to: 'home#testimonials', as: :home_testimo
  get '/event/:id', to: 'home#gallery', as: :category_event
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonis#all_testimoni', as: :all_testimoni
  get 'admin/users/', to: 'users#all_user', as: :all_user
  get 'admin/announcements/', to: 'news#all_news', as: :all_news
  get 'admin/users/change-password/:id', to: 'users#edit_password', as: :edit_password
  get 'admin/categories', to: 'categories#all_category', as: :all_category
  delete '/events/:event_id/galleries/:id', to: 'galleries#delt', as: :delete_gallery
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :galleries

  validates :slug, uniqueness: true, presence: true
  before_validation :generate_slug


  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category, only: [:edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy, :all_category]

  def new
    @category = Category.new
    render layout: "admin"
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to new_category_url
    else
      render 'new'
    end
  end

  def edit
    render layout: "admin"
  end

  def all_category
    @tests = Category.all.order('created_at desc')
    render layout: "admin"
  end

  def update
    if @category.update(category_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "Category" %>
      </div>
      <div class="btn_x">
        <%= f.submit "Submit", class: "btn btn-default btn-x" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/all_category.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">All Category</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_category_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_category_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <div class="testimonaial edbsg" style="width: 100%;">
      <div class="leyr titl">
        <p class="hsy">all the category that have been added <span class="pull-right hgdr"><%= @tests.count %></span></p>
      </div>
      <div class="dhjwt">
        <ul class="cbdq">
          <% @tests.each_with_index do |test, index| %>
            <li class="ang <%= 'cvdg' if (index + 1)%2 == 0 %>">
              <ul class="list-inline najhs">
                <li class="name_" style="width: 200px !important;"><%= test.name %></li>
                <li class="created_at_"  style="width: 135px !important; border-right: 1px solid #e7ebf1 !important;"><%= test.created_at.strftime("%d %B %Y") %></li>
                <li class="actions_">
                  <ul class="list-inline ahster">
                    <li><%= link_to edit_category_path(test) do %><i class="fa fa-pencil-square-o" aria-hidden="true"></i><% end %></li>
                    <li><%= link_to test, method: :delete do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></li>
                  </ul>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.category__').addClass('aktif');
</script>

app/views/categories/edit.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">Edit  Category</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_category_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_category_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render 'categories/form' %>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.category__').addClass('aktif');
</script>

app/views/categories/new.html.erb
<div class="contain">
  <div class="top_tit">
    <h2 class="title">Add Category</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_category_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_category_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render 'categories/form' %>
  </div>
</div>
<script>
$('.respond').removeClass("aktif");      
$('.category__').addClass('aktif');
</script>