config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :categories
  resources :events
  resources :testimonis
  resources :sliders
  resources :news
  resources :contacts, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/event', to: 'home#event', as: :home_event
  get '/contact', to: 'home#contact', as: :home_contact
  get '/about', to: 'home#about', as: :home_about
  get '/client-says', to: 'home#testimonials', as: :home_testimo
  get '/event/:id', to: 'home#gallery', as: :category_event
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonis#all_testimoni', as: :all_testimoni
  get 'admin/users/', to: 'users#all_user', as: :all_user
  get 'admin/announcements/', to: 'news#all_news', as: :all_news
  get 'admin/users/change-password/:id', to: 'users#edit_password', as: :edit_password
  get 'admin/categories', to: 'categories#all_category', as: :all_category
  delete '/events/:event_id/galleries/:id', to: 'galleries#delt', as: :delete_gallery
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :galleries

  validates :slug, uniqueness: true, presence: true
  before_validation :generate_slug


  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  attribute :phone, validate: true
  attribute :message, validate: true
  attribute :nickname, :captcha => true

  def headers 
    {
    :subject => "Email dari Client",
    :to => "ruangide.yk@gmail.com",
    :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :galleries, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :galleries, reject_if: :all_blank, allow_destroy: true
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  
  belongs_to :event
  belongs_to :category
  mount_uploader :image, GalleryUploader

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  mount_uploader :slider, SliderUploader
end

app/models/testimoni.rb
class Testimoni < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader 
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :profile, ProfileUploader
  attr_accessor :remember_token, :reset_token
  before_save :email_downcase

  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, presence: true, length: {minimum: 9}, :on => :update, :unless => lambda{ |user| user.password.blank? }#, :on => :create, :unless => lambda{ |user| user.password.blank? }
  validates :password_confirmation, presence: true, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # def authenticated?(remember_token)
  #   return false if remember_digest.nil?
  #   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if remember_digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  has_many :events

  private
  
  def email_downcase
    self.email = email.downcase
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news = News.all.order('created_at desc')
  end

  def event
    @categories = Category.all.order('name asc')
  end

  def contact
    @contact = Contact.new
  end

  def about
    
  end

  def testimonials
    @testimonis = Testimoni.all.order('created_at desc')
  end

  def gallery
    @category = Category.find_by_slug!(params[:id])
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  before_action :set_news, only: [:update, :edit, :destroy]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @news = News.new
    render layout: "admin"
  end

  def create
    @news = News.new(params_news)
    if @news.save
      redirect_to all_news_url
    else
      render 'new'
    end
  end

  def edit
    render layout: "admin"
  end

  def update
    if @news.update(params_news)
      redirect_to all_news_url
    else
      render 'edit'
    end
  end

  def destroy
    @news.destroy
    redirect_to all_news_url
  end

  def all_news
    @news = News.all.order('created_at desc')
    render layout: "admin"
  end

  private

  def set_news
    @news = News.find(params[:id])
  end

  def params_news
    params.require(:news).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end


  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/testimonis_helper.rb
module TestimonisHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_url, notice: "Please sign in."
    end
  end

  def redirect_signed_in_user
    unless signed_in?
      redirect_to root_url, notice: "Please sign in."
    end
  end

  def redirect_signed_in_user_from_signin
    redirect_to user_url(current_user) if signed_in?
  end
end

app/views/admins/dashboard.html.erb
<div class="contain">
  <div class="top_tit">
   <h2 class="title">Dashboard</h2>
  </div>
  <div class="cont_ii">
    <div class="event_ edbsg">
      <div class="titl">
        <p class="hsy">all the events that have been added <span class="pull-right hgdr"><%= @events.count %></span></p>
      </div>
      <div class="dhjwt">
        <ul class="cbdq">
          <% @events.each_with_index do |event, index| %>
            <li class="ang <%= 'cvdg' if (index + 1)%2 == 0 %>">
              <ul class="list-inline najhs">
                <li class="name_"><%= event.name %></li>
                <li class="user_"><%= event.user.username %></li>
                <li class="created_at_"><%= event.created_at.strftime("%d %B %Y") %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="testimonaial edbsg">
      <div class="leyr titl">
        <p class="hsy">all the testimonial that have been added <span class="pull-right hgdr"><%= @tests.count %></span></p>
      </div>
      <div class="dhjwt">
        <ul class="cbdq">
          <% @tests.each_with_index do |test, index| %>
            <li class="ang <%= 'cvdg' if (index + 1)%2 == 0 %>">
              <ul class="list-inline najhs">
                <li class="name_"><%= truncate(test.name, length: 19) %></li>
                <li class="user_ content_"><%= truncate(test.content, length: 29) %></li>
                <li class="created_at_"><%= test.created_at.strftime("%d %B %Y") %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="testimonaial edbsg">
      <div class="leyr titl">
        <p class="hsy">all the announcement  have been added <span class="pull-right hgdr"><%= @news.count %></span></p>
      </div>
      <div class="dhjwt">
        <ul class="cbdq">
          <% @news.each_with_index do |test, index| %>
            <li class="ang <%= 'cvdg' if (index + 1)%2 == 0 %>">
              <ul class="list-inline najhs">
                <li class="name_"><%= truncate(test.title, length: 19) %></li>
                <li class="user_ content_"><%= truncate(test.content, length: 29) %></li>
                <li class="created_at_"><%= test.created_at.strftime("%d %B %Y") %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="sliders edbsg">
       <div class="leyr titl">
        <p class="hsy">all the testimonial that have been added <span class="pull-right hgdr"><%= @sliders.count %></span></p>
      </div>
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <% @sliders.each_with_index do |slider, index| %>
            <div class="item <%= 'active' if index == 0 %>">
            <%= image_tag slider.slider_url(:thumbso) %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html id="top_nav">
  <head>
    <title>
      <%= if content_for?(:title) then yield(:title) end %>
        ~ Ruang Ide
    </title>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Great+Vibes|Montez|Over+the+Rainbow|Rancho|Roboto+Slab:300,400,700|Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <body>
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>" style="margin-bottom: 0px; text-align: center;position: absolute;z-index: 999;width: 100%;">
      <%= msg %> <span id= "close_alt" class="pull-right fa fa-close" style="cursor: pointer;"></span>
    </div>
    <% end %>
    <div class="navbar navbar-default top_nav">
      <div class="container-fluid nejg">
        <div class="navbar-header">
          <%= link_to "RUANG IDE", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right ghkjh">
          <li class="dropdown">
            <% if !current_user.profile.present? %>
              <%= image_tag "default/default_profile.png" %>
            <% else %>
              <%= image_tag current_user.profile_url(:thumb) %>
            <% end %>
            <a class="jdfu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= current_user.username %></a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "SETTING", edit_user_path(current_user), class: "sdh" %></li> 
              <li><%= link_to "LOGOUT", logout_path, method: "delete", class: "sdh" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <div class="navbar navbar-default left_nav">
      <div class="ahg">
        <p class="dash_brd respond aktif"><i class="fa fa-tachometer" aria-hidden="true"></i><%= link_to "Dashboard", dashboard_path %></p>
        <p class="event__ respond"><i class="fa fa-suitcase" aria-hidden="true"></i><%= link_to "Event", all_event_url %></p>
        <p class="slider__ respond"><i class="fa fa-retweet" aria-hidden="true"></i><%= link_to "Slider", all_slider_url %></p>
        <p class="testimonial__ respond"><i class="fa fa-users" aria-hidden="true"></i><%= link_to "Testimonial", all_testimoni_url %></p>
        <p class="news__ respond"><i class="fa fa-newspaper-o" aria-hidden="true"></i><%= link_to "Announcement", all_news_url %></p>
        <p class="category__ respond"><i class="fa fa-cubes" aria-hidden="true"></i><%= link_to "Category", all_category_url %></p>
        <p class="admin__ respond"><i class="fa fa-user" aria-hidden="true"></i><%= link_to "Users", all_user_url %></p>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= if content_for?(:title) then yield(:title) end %>
    ~ Ruang Ide
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Domine:400,700" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <canvas id="canvas" class="noise"></canvas>
  <div class="why_always_me" style="background-image: url(<%= Slider.all.order('created_at desc').limit(1).map{ |slider| slider.slider }.join("") %>)">
    <div class="gras">
      <div class="make_me_streess"></div>
    </div>
    <div class="i_dont_know">
      <div class="container-fluid">
        <button class="menu_bar" id="mnu_bar">
          <div class="c-har">
            <div class="ch-h -right"></div>
            <div class="ch-h -left"></div>
            <span class="bar-top"></span>
            <span class="bar-middle"></span>
            <span class="bar-bottom"></span>
          </div>
        </button>
        <div class="nav_slide">
          <div class="first_nav">
            <div class="container">
              <ul class="rise-up">
                <li class="home_"><a href="/" data-turbolinks="false"><span>RUANG IDE</span></a></li>
                <li class="ttk_"><a href="/about" data-turbolinks="false"><span>TENTANG KAMI</span></a></li>
                <li class="event_"><a href="/event" data-turbolinks="false"><span>GALERI</span></a></li>
                <li class="testimn_"><a href="/client-says" data-turbolinks="false"><span>TESTIMONI</span></a></li>
                <li class="contact_"><a href="/contact" data-turbolinks="false"><span>HUBUNGI KAMI</span></a></li>
              </ul>
            </div>
          </div>
        </div>
        <%= yield %>
      </div>    
    </div>
  </div>
  <div class="footer">
    <div class="container-fluid">
      <ul class="list-inline pull-right sosmed">
        <li><a href="https://www.facebook.com/profile.php?id=100011330527733"><i class="fa fa-facebook" aria-hidden="true" target="_blank"></i></a></li>
        <li><a href="https://www.instagram.com/ruangide_jogja/"><i class="fa fa-instagram" aria-hidden="true" target="_blank"></i></a></li>
        <li><a href="https://twitter.com/RuangIde_yk?s=07"><i class="fa fa-twitter" aria-hidden="true" target="_blank"></i></a></li>
      </ul>
      <ul class="pull-left copyright">
        <li>Copyright 2016 © Ruang Ide All rights reserved</li>
      </ul>
      <div class="clear"></div>
    </div>
  </div>
</body>
</html>